name: featurama_test_app
description: Test app for Featurama Flutter SDK
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  featurama:
    path: ../../sdks/flutter

flutter:
  uses-material-design: true
